import type { ReportData } from "../schemas/biomarker.js";

export const mockReportData: ReportData = {
  patient: {
    dateOfBirth: "1978-05-15",
    age: 47,
    sex: "male",
    bloodType: "A",
    rhFactor: "+",
    reportDate: "2024-03-20",
  },
  biomarkers: [
    {
      originalName: "Hemoglobina",
      englishName: "Hemoglobin",
      value: 15.2,
      qualifier: "none",
      originalUnit: "g/dL",
      standardizedUnit: "g/dL",
      referenceMin: 13.0,
      referenceMax: 17.0,
      category: "Complete Blood Count",
    },
    {
      originalName: "Hematocrito",
      englishName: "Hematocrit",
      value: 45.5,
      qualifier: "none",
      originalUnit: "%",
      standardizedUnit: "%",
      referenceMin: 40.0,
      referenceMax: 50.0,
      category: "Complete Blood Count",
    },
    {
      originalName: "Leucocitos",
      englishName: "White Blood Cells",
      value: 7.2,
      qualifier: "none",
      originalUnit: "x10³/mm³",
      standardizedUnit: "10³/µL",
      referenceMin: 4.0,
      referenceMax: 10.0,
      category: "Complete Blood Count",
    },
    {
      originalName: "Colesterol Total",
      englishName: "Total Cholesterol",
      value: 195,
      qualifier: "none",
      originalUnit: "mg/dL",
      standardizedUnit: "mg/dL",
      referenceMin: 0,
      referenceMax: 200,
      category: "Lipid Panel",
    },
    {
      originalName: "Colesterol LDL",
      englishName: "LDL Cholesterol",
      value: 125,
      qualifier: "none",
      originalUnit: "mg/dL",
      standardizedUnit: "mg/dL",
      referenceMin: 0,
      referenceMax: 130,
      category: "Lipid Panel",
    },
    {
      originalName: "Colesterol HDL",
      englishName: "HDL Cholesterol",
      value: 55,
      qualifier: "none",
      originalUnit: "mg/dL",
      standardizedUnit: "mg/dL",
      referenceMin: 40,
      referenceMax: null,
      category: "Lipid Panel",
    },
    {
      originalName: "Triglicéridos",
      englishName: "Triglycerides",
      value: 145,
      qualifier: "none",
      originalUnit: "mg/dL",
      standardizedUnit: "mg/dL",
      referenceMin: 0,
      referenceMax: 150,
      category: "Lipid Panel",
    },
    {
      originalName: "Glucosa",
      englishName: "Glucose",
      value: 92,
      qualifier: "none",
      originalUnit: "mg/dL",
      standardizedUnit: "mg/dL",
      referenceMin: 70,
      referenceMax: 100,
      category: "Glucose Metabolism",
    },
    {
      originalName: "Hemoglobina Glicosilada (HbA1c)",
      englishName: "HbA1c (NGSP)",
      value: 5.4,
      qualifier: "none",
      originalUnit: "%",
      standardizedUnit: "%",
      referenceMin: 4.0,
      referenceMax: 5.6,
      category: "Glucose Metabolism",
    },
    {
      originalName: "Creatinina",
      englishName: "Creatinine",
      value: 1.05,
      qualifier: "none",
      originalUnit: "mg/dL",
      standardizedUnit: "mg/dL",
      referenceMin: 0.7,
      referenceMax: 1.3,
      category: "Renal Function",
    },
    {
      originalName: "Urea",
      englishName: "Urea",
      value: 35,
      qualifier: "none",
      originalUnit: "mg/dL",
      standardizedUnit: "mg/dL",
      referenceMin: 15,
      referenceMax: 45,
      category: "Renal Function",
    },
    {
      originalName: "Ácido Úrico",
      englishName: "Uric Acid",
      value: 6.2,
      qualifier: "none",
      originalUnit: "mg/dL",
      standardizedUnit: "mg/dL",
      referenceMin: 3.5,
      referenceMax: 7.2,
      category: "Renal Function",
    },
    {
      originalName: "Proteína C Reactiva",
      englishName: "CRP",
      value: 0.8,
      qualifier: "<",
      originalUnit: "mg/L",
      standardizedUnit: "mg/L",
      referenceMin: null,
      referenceMax: 5.0,
      category: "Inflammation Markers",
    },
  ],
};
